/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Control.ControlPosts;
import Control.ControlTags;
import Control.ControlUsers;
import Entities.Comment;
import Entities.Post;
import Entities.Tag;
import Entities.User;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.bson.types.ObjectId;

/**
 *
 * @author Brenda Bojorquez
 */
public class Principal extends javax.swing.JFrame {

    private User user;
    private ControlPosts controlPost;
    private ControlTags controlTag;
    private ControlUsers controlUser;
    
    /**
     * Creates new form Principal
     */
    public Principal(User user) {
        this.user=user;
        controlPost=new ControlPosts();
        controlTag=new ControlTags();
        controlUser=new ControlUsers();
        initComponents();
        lblName.setText(user.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        lblLogOut = new javax.swing.JLabel();
        lblSetup = new javax.swing.JLabel();
        pnlUser = new javax.swing.JPanel();
        lblRobot = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        pnlPost = new javax.swing.JPanel();
        lblPost = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPost = new javax.swing.JTextArea();
        btnPost = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPosts = new javax.swing.JList<>();
        txtComment = new javax.swing.JTextField();
        btnComentar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pnlMenu.setBackground(new java.awt.Color(64, 103, 127));

        lblLogOut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLogOut.setForeground(new java.awt.Color(255, 255, 255));
        lblLogOut.setText("LOGOUT");
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
        });

        lblSetup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/setup.png"))); // NOI18N
        lblSetup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSetupMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogOut)
                .addGap(18, 18, 18)
                .addComponent(lblSetup)
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSetup)
                    .addComponent(lblLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlUser.setBackground(new java.awt.Color(255, 255, 255));

        lblRobot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        lblName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblName.setText("1234");

        pnlPost.setBackground(new java.awt.Color(255, 255, 255));

        lblPost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPost.setText("¿Qué estás pensando?");

        txtPost.setColumns(20);
        txtPost.setRows(5);
        jScrollPane1.setViewportView(txtPost);

        btnPost.setText("Post");
        btnPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostActionPerformed(evt);
            }
        });

        btnDelete.setText("Borrar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPostLayout = new javax.swing.GroupLayout(pnlPost);
        pnlPost.setLayout(pnlPostLayout);
        pnlPostLayout.setHorizontalGroup(
            pnlPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPost)
                    .addGroup(pnlPostLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPost)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPostLayout.setVerticalGroup(
            pnlPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPostLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlUserLayout = new javax.swing.GroupLayout(pnlUser);
        pnlUser.setLayout(pnlUserLayout);
        pnlUserLayout.setHorizontalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUserLayout.createSequentialGroup()
                        .addComponent(lblRobot)
                        .addGap(18, 18, 18)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUserLayout.setVerticalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRobot)
                    .addGroup(pnlUserLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lstPosts.setModel(new DefaultComboBoxModel<Post>(this.cargarPosts()));
        jScrollPane2.setViewportView(lstPosts);

        btnComentar.setText("Comentar");
        btnComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtComment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnComentar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComentar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostActionPerformed
        Post post = new Post();
        post.setTags(getTags());
        post.setDateHour(new Date());
        post.setComments(new ArrayList<>());
        post.setText(txtPost.getText());
        post.setUser(user.getId());
        if (this.controlPost.insert(post)) {
            lstPosts.setListData(cargarPosts());
            txtPost.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo publicar el post", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnPostActionPerformed

    private void btnComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentarActionPerformed
        Post post=lstPosts.getSelectedValue();
        Comment com=new Comment(new ObjectId(), txtComment.getText(), new Date(), user.getId());
        post.addComment(com);
        controlPost.update(post);
        txtComment.setText("");
        lstPosts.setListData(cargarPosts());
    }//GEN-LAST:event_btnComentarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Post post = lstPosts.getSelectedValue();
        if (this.user.getId().equals(post.getUser())) {
            controlPost.remove(post);
            lstPosts.setListData(cargarPosts());
        } else{
            JOptionPane.showMessageDialog(this, "No estás autorizado para eliminar este post");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
        int answer=JOptionPane.showConfirmDialog(this, "¿Seguro que deseas salir?");
        if(answer==0){
            Inicio i=new Inicio();
            i.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lblLogOutMouseClicked

    private void lblSetupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetupMouseClicked
        Setup s=new Setup(user);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSetupMouseClicked

    private Post[] cargarPosts(){
        List<Post> posts=controlPost.find();
        Post[] array=new Post[posts.size()];
        String p=null;
        int i=0;
        for (Post post : posts) {
            array[i]=post;
            i++;
        }
        return array;
    }
    
    private ArrayList<Tag> getTags() { 
        
        ArrayList<Tag> tags = new ArrayList<>();
        Pattern pattern = Pattern.compile("[#][a-z]*");
        Matcher match = null;
        String cadenas[];
        cadenas = txtPost.getText().split(" ");
        List<Tag> tags2 = controlTag.find();
        for (int i = 0; i < cadenas.length; i++) {
            match = pattern.matcher(cadenas[i]);
            if (match.find()) {
                tags.add(new Tag(cadenas[i], new ObjectId()));
            }
            if (tags2.isEmpty()) {
                tags2.add(new Tag(cadenas[i], new ObjectId()));
            } else {
                for (Tag tag1 : tags2) {
                    if (!tag1.equals(cadenas[i])) {
                        tags2.add(new Tag(cadenas[i], new ObjectId()));
                    }
                }
            }
        }
        
        return tags;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComentar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPost;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPost;
    private javax.swing.JLabel lblRobot;
    private javax.swing.JLabel lblSetup;
    private javax.swing.JList<Post> lstPosts;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPost;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JTextField txtComment;
    private javax.swing.JTextArea txtPost;
    // End of variables declaration//GEN-END:variables
}
