package Enums;

/**
 *
 * @author Brenda Bojorquez
 */
public enum MovieGenre {
    ACTION,ADVENTURES,ANIMATED,BIOPICS,BRITISH,COMEDY,CRIME,CLASSIC,CULT,
    DISASTER,DOCUMENTARY,DRAMA,FAMILY,FANTASY,HISTORICAL,HORROR,MUSICALS,
    MYSTERY,ROMANCE,SCIFI,SPORTS,SUPERHERO,SUPERNATURAL,THRILLER,WAR,
    WESTERN,ZOMBIES
}
